services:
  auth:
    build: ./auth
    ports:
      - "8000:8000"

  workout:
    build: ./workout
    ports:
      - "8002:8002"
    environment:
      - AUTH_BASE_URL=http://auth:8000

  calculator:
    build: ./calorie-calc
    ports:
      - "8001:8001"

  frontend:
      build: ./frontend
      ports:
        - "5173:5173"
      env_file:
        - ./frontend/.env
      command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
