# Save as: kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30073   # frontend NodePort
        hostPort: 30073
      - containerPort: 30080   # auth NodePort
        hostPort: 30080
      - containerPort: 30081   # calculator
        hostPort: 30081
      - containerPort: 30082   # workout
        hostPort: 30082
