# Generated by Django 5.2.7 on 2025-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_sets_workout_user_workout_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.CharField(default='Monday', max_length=12),
            preserve_default=False,
        ),
    ]
